local _, Quiz = ...

Quiz.Lore:Add(
    "mop",
    "Mists of Pandaria",
    "https://news.blizzard.com/en-us/article/24213958/unveiling-pandaria-a-journey-through-the-zones-of-mists-of-pandaria-classic",
    {
        {
            "jade_forest",
            "easy",
            "Which forest contains the Temple of the Jade Serpent?",
            { "The Jade Forest", "Crystalsong Forest", "Terokkar Forest", "Elwynn Forest" },
            1,
        },
        {
            "halfhill_farmers",
            "easy",
            "Which farming faction gathers around Halfhill Market?",
            { "The Anglers", "The Tillers", "The Lorewalkers", "The Golden Lotus", "The Klaxxi" },
            2,
        },
        {
            "southern_jungle",
            "medium",
            "Which jungle borders Pandaria's southern coast?",
            { "The Dread Wastes", "Townlong Steppes", "Krasarang Wilds", "Kun-Lai Summit" },
            3,
        },
        {
            "alliance_landing",
            "medium",
            "What is the Alliance stronghold on the Krasarang coast called?",
            { "Paw'don Village", "Dawn's Blossom", "Domination Point", "Lion's Landing", "Sentinel Hill" },
            4,
        },
        {
            "horde_landing",
            "medium",
            "Which Krasarang stronghold was built for the Horde's Pandaria campaign?",
            { "Domination Point", "Lion's Landing", "Westwind Rest", "Zouchin Village" },
            1,
        },
        {
            "burlap_traders",
            "medium",
            "Which small traders travel the Burlap Trail?",
            { "Hozen", "Grummles", "Virmen", "Jinyu", "Yaungol", "Tol'vir" },
            2,
        },
        {
            "monastery_region",
            "easy",
            "Where is the Shado-Pan Monastery?",
            { "The Jade Forest", "Krasarang Wilds", "Kun-Lai Summit", "The Wandering Isle" },
            3,
        },
        {
            "lotus_charge",
            "medium",
            "Which sacred valley is protected by the Golden Lotus?",
            {
                "The Valley of Trials",
                "The Valley of Emperors",
                "The Valley of the Four Winds",
                "The Vale of Eternal Blossoms",
            },
            4,
        },
    }
)

Quiz.Lore:Add(
    "mop",
    "Mists of Pandaria",
    "https://news.blizzard.com/en-us/article/24223012/brave-the-challenges-within-the-dungeons-of-pandaria",
    {
        {
            "mari_people",
            "medium",
            "Wise Mari belongs to which people?",
            { "Jinyu", "Hozen", "Mogu", "Pandaren", "Grummles" },
            1,
        },
        {
            "mari_fountain",
            "very_hard",
            "Which fountain supplied Wise Mari with visions?",
            {
                "The Fountain of Hope",
                "The Fountain of the Ever-Seeing",
                "The Moonwell of Purity",
                "The Wellspring of Eternity",
            },
            2,
        },
        {
            "stonestep_library",
            "hard",
            "Who struggles to restore the Jade Serpent temple's corrupted story manifestations?",
            { "Lorewalker Cho", "Liu Flameheart", "Lorewalker Stonestep", "Taran Zhu" },
            3,
        },
        {
            "liu_rebirth",
            "hard",
            "Liu Flameheart tends the cycle of rebirth of which Celestial?",
            { "Chi-Ji", "Niuzao", "Xuen", "Yu'lon" },
            4,
        },
        {
            "ook_party",
            "very_hard",
            "What does Ook-Ook call his brewery party?",
            { "Ookapalooza", "Brewfest", "The Kegmoot", "The Stormstout Jubilee", "The Feast of Winter Veil" },
            1,
        },
        {
            "hoptallus_people",
            "medium",
            "The enormous crop-devourer Hoptallus is one of which creatures?",
            { "Hozen", "Virmen", "Yaungol", "Saurok" },
            2,
        },
        {
            "yan_zhu_creator",
            "hard",
            "Whose experimental ale created Yan-Zhu the Uncasked?",
            { "Chen Stormstout's", "Li Li Stormstout's", "Uncle Gao's", "Bo's", "Mudmug's" },
            3,
        },
        {
            "palace_ruler",
            "medium",
            "Which weaponmaster asserts his rule from Mogu'shan Palace?",
            { "Feng", "Shan Bu", "Lao-Fe", "Xin" },
            4,
        },
        {
            "gekkan_people",
            "hard",
            "Gekkan leads raiders of which people into Mogu'shan Palace?",
            { "Saurok", "Hozen", "Mantid", "Jinyu", "Yaungol" },
            1,
        },
        {
            "cloudstrike_students",
            "hard",
            "Before his corruption, Gu Cloudstrike trained which Shado-Pan specialists?",
            { "Beast tamers", "Spellcasters", "Brewmasters", "Assassins" },
            2,
        },
        {
            "taran_corruption",
            "medium",
            "Which sha corrupts Taran Zhu in Shado-Pan Monastery?",
            {
                "The Sha of Fear",
                "The Sha of Pride",
                "The Sha of Hatred",
                "The Sha of Doubt",
                "The Sha of Despair",
                "The Sha of Anger",
            },
            3,
        },
        {
            "living_ram",
            "hard",
            "Which mantid serves as a living battering ram at the Gate of the Setting Sun?",
            { "Kip'tilak", "Ga'dok", "Ri'mok", "Raigonn" },
            4,
        },
        {
            "jinbak_material",
            "very_hard",
            "What does Vizier Jin'bak collect to make siege weapons?",
            { "Tree sap", "Ghost iron", "Cloud serpent venom", "Jade dust", "Mushan blood" },
            1,
        },
        {
            "neronok_rival",
            "very_hard",
            "Wing Leader Ner'onok considers himself superior to which general?",
            { "General Nazgrim", "General Pa'valak", "General Husam", "General Umbriss" },
            2,
        },
    }
)

Quiz.Lore:Add(
    "mop",
    "Mists of Pandaria",
    "https://worldofwarcraft.blizzard.com/en-us/news/24216437/mists-of-pandaria-classic-enter-the-mogushan-vaults-raid-now-live",
    {
        {
            "feng_name",
            "very_hard",
            "What was Feng the Accursed called before his curse?",
            { "Shan Bu", "Lao-Fe", "Feng Shri", "Xin", "Qiang" },
            3,
        },
        {
            "feng_offense",
            "hard",
            "What accusation led to the curse placed upon Feng?",
            { "Deserting a battlefield", "Killing the emperor", "Freeing pandaren slaves", "Stealing from the vaults" },
            4,
        },
        {
            "garajal_force",
            "medium",
            "Gara'jal leads which trolls in the assault on Mogu'shan Vaults?",
            { "Zandalari", "Amani", "Drakkari", "Farraki", "Gurubashi" },
            1,
        },
        {
            "meng_title",
            "hard",
            "Which Spirit King is called the Demented?",
            { "Zian", "Meng", "Qiang", "Subetai" },
            2,
        },
        {
            "zian_title",
            "hard",
            "Which Spirit King bears the title of the Endless Shadow?",
            { "Meng", "Subetai", "Zian", "Qiang" },
            3,
        },
        { "swift_king", "hard", "Which Spirit King is known as the Swift?", { "Qiang", "Meng", "Zian", "Subetai" }, 4 },
        {
            "elegon_form",
            "medium",
            "What form does Elegon take in Mogu'shan Vaults?",
            { "A celestial dragon", "A stone quilen", "A jade golem", "An amber mantid", "A thunder phoenix" },
            1,
        },
        {
            "sleeping_army",
            "medium",
            "What army waits in the core chamber of Mogu'shan Vaults?",
            { "Undead pandaren", "Stone soldiers", "Captured demons", "Bronze dragons" },
            2,
        },
    }
)

Quiz.Lore:Add(
    "mop",
    "Mists of Pandaria",
    "https://news.blizzard.com/en-us/article/24249602/take-on-lei-shen-the-throne-of-thunder-raid-is-now-live",
    {
        {
            "jinrokh_blessing",
            "medium",
            "Who gave Jin'rokh the Breaker his storm power?",
            { "Hakkar", "Rezan", "Lei Shen", "Vol'jin" },
            3,
        },
        {
            "horridon_rider",
            "hard",
            "Horridon is the famed mount of which Zandalari war-god?",
            { "Jin'rokh", "Gara'jal", "Kazra'jin", "Jalak", "Zul" },
            4,
        },
        {
            "kazrajin_tribe",
            "hard",
            "Which tribe does Kazra'jin represent on the Council of Elders?",
            { "Amani", "Gurubashi", "Drakkari", "Farraki" },
            1,
        },
        {
            "sul_tribe",
            "hard",
            "Sul the Sandcrawler represents which troll tribe?",
            { "Amani", "Farraki", "Gurubashi", "Drakkari", "Darkspear" },
            2,
        },
        {
            "malakk_tribe",
            "medium",
            "Frost King Malakk belongs to which troll tribe?",
            { "Farraki", "Darkspear", "Drakkari", "Gurubashi" },
            3,
        },
        {
            "marli_tribe",
            "hard",
            "High Priestess Mar'li represents which tribe in Lei Shen's citadel?",
            { "Drakkari", "Amani", "Farraki", "Gurubashi" },
            4,
        },
        {
            "tortos_origin",
            "hard",
            "Before flesh-shaping magic changed him, Tortos was what?",
            { "A dragon turtle", "A crocolisk", "A basilisk", "A cloud serpent", "A mushan" },
            1,
        },
        {
            "megaera_origin",
            "hard",
            "Before becoming a hydra, Megaera was what?",
            { "A dragon turtle", "A cloud serpent", "A wind serpent", "A devilsaur" },
            2,
        },
        {
            "jikun_attraction",
            "hard",
            "What first attracted Ji-Kun to the shaft beneath Lei Shen's keep?",
            {
                "A clutch of dragon eggs",
                "A mogu summoning ritual",
                "Discarded flesh-shaping experiments",
                "The Thunder King's singing",
            },
            3,
        },
        {
            "durumu_purpose",
            "hard",
            "What was Durumu created to detect in Lei Shen's followers?",
            { "Illness", "Hidden wealth", "Titan ancestry", "Betrayal" },
            4,
        },
        {
            "saurok_makers",
            "medium",
            "Which people created the saurok through flesh-shaping?",
            { "Mogu", "Jinyu", "Mantid", "Pandaren", "Zandalari" },
            1,
        },
        {
            "animus_emotion",
            "hard",
            "Which emotion did Lei Shen pour into the Dark Animus?",
            { "Grief", "Rage", "Fear", "Doubt", "Despair" },
            2,
        },
    }
)

Quiz.Lore:Add(
    "mop",
    "Mists of Pandaria",
    "https://news.blizzard.com/en-us/article/24252017/mists-of-pandaria-classic-siege-of-orgrimmar-raid-now-live",
    {
        {
            "besieged_warchief",
            "easy",
            "Which Warchief is overthrown during the Siege of Orgrimmar?",
            { "Thrall", "Vol'jin", "Garrosh Hellscream", "Sylvanas Windrunner" },
            3,
        },
        {
            "unearthed_heart",
            "easy",
            "Garrosh draws power from the heart of which Old God?",
            { "C'Thun", "N'Zoth", "Yogg-Saron", "Y'Shaarj" },
            4,
        },
        {
            "last_burden",
            "medium",
            "Which burden did Shaohao fail to cast away?",
            { "Pride", "Fear", "Anger", "Doubt", "Hatred", "Despair" },
            1,
        },
        {
            "immerseus_origin",
            "hard",
            "Immerseus forms from the corruption of which waters?",
            { "The Sunwell", "The Pools of Power", "The Well of Eternity", "The Fountain of the Ever-Seeing" },
            2,
        },
        {
            "galakras_rider",
            "medium",
            "Who rides Galakras while directing Orgrimmar's naval defenses?",
            { "Kardris", "Garona Halforcen", "Warlord Zaela", "Aggra" },
            3,
        },
        {
            "juggernaut_shape",
            "medium",
            "Garrosh's Iron Juggernaut is modeled on which animal?",
            { "A wolf", "A devilsaur", "A kodo", "A scorpion", "A ravager" },
            4,
        },
        {
            "dark_shaman_pair",
            "hard",
            "Which pair serves as Garrosh's Kor'kron Dark Shaman?",
            { "Haromm and Kardris", "Drek'Thar and Rehgar", "Muln and Nobundo", "Zian and Meng" },
            1,
        },
        {
            "nazgrim_loyalty",
            "medium",
            "Which Horde general defends Garrosh out of duty despite the rebellion?",
            { "General Husam", "General Nazgrim", "General Drakkisath", "General Pa'valak" },
            2,
        },
        {
            "willing_infusion",
            "hard",
            "Which lieutenant volunteers to receive Y'Shaarj's power for Garrosh?",
            { "Nazgrim", "Blackfuse", "Malkorok", "Zaela", "Jalak" },
            3,
        },
        {
            "thok_capture",
            "hard",
            "Where did Garrosh's men capture Thok the Bloodthirsty?",
            { "Un'Goro Crater", "Zandalar", "Sholazar Basin", "The Isle of Giants" },
            4,
        },
        {
            "blackfuse_name",
            "hard",
            "What is Siegecrafter Blackfuse's first name?",
            { "Helix", "Gazlowe", "Hobart", "Mogul", "Rixxa" },
            1,
        },
        {
            "plunder_store",
            "medium",
            "Where did Garrosh store his plundered pandaren, mogu, and mantid treasures?",
            {
                "A vault beneath Thunder Bluff",
                "A warehouse beneath Orgrimmar",
                "The Hall of Explorers",
                "The Undercity Royal Quarter",
            },
            2,
        },
    }
)

Quiz.Lore:Add(
    "mop",
    "Mists of Pandaria",
    "https://news.blizzard.com/en-us/article/24216159/mists-of-pandaria-classic-travel-through-time-in-the-burdens-of-shaohao",
    {
        {
            "last_emperor",
            "easy",
            "Who was Pandaria's last pandaren emperor?",
            { "Lei Shen", "Kang", "Shaohao", "Liu Lang" },
            3,
        },
        {
            "future_reader",
            "hard",
            "Whom did Shaohao ask to read his future?",
            { "The Monkey King", "The Jade Serpent", "The Black Ox", "The Great Waterspeaker" },
            4,
        },
        {
            "doubt_counsel",
            "medium",
            "Which Celestial did Shaohao seek for wisdom while struggling with doubt?",
            { "The Jade Serpent", "The White Tiger", "The Red Crane", "The Black Ox" },
            1,
        },
        {
            "fear_counsel",
            "hard",
            "Which Celestial advised Shaohao in the mantid lands?",
            { "The Red Crane", "The Black Ox", "The White Tiger", "The Jade Serpent" },
            2,
        },
        {
            "anger_challenge",
            "hard",
            "Which Celestial challenged the anger Shaohao carried when seeking an army?",
            { "The Black Ox", "The Jade Serpent", "The White Tiger", "The Red Crane" },
            3,
        },
        {
            "despair_trap",
            "hard",
            "Where did Shaohao become trapped while struggling with despair?",
            { "A snowdrift", "A mogu prison", "A burning forest", "A swamp" },
            4,
        },
    }
)

Quiz.Lore:Add(
    "mop",
    "Mists of Pandaria",
    "https://worldofwarcraft.blizzard.com/en-us/news/8520756/know-thy-enemy-portrait-of-a-thunder-king",
    {
        {
            "thunder_king",
            "easy",
            "Which mogu ruler is known as the Thunder King?",
            { "Lei Shen", "Xin", "Lao-Fe", "Shan Bu" },
            1,
        },
        {
            "birth_era",
            "very_hard",
            "Lei Shen was born during which age of mogu history?",
            { "The Age of Mortals", "The Age of a Hundred Kings", "The Long Vigil", "The Age of the Seven Stars" },
            2,
        },
        {
            "father_station",
            "very_hard",
            "What was Lei Shen's father's position among the mogu?",
            { "A slave", "A temple caretaker", "A warlord", "A Lorewalker" },
            3,
        },
        {
            "wall_builder",
            "medium",
            "Which ruler ordered the construction of the Serpent's Spine?",
            { "Shaohao", "Kang", "Xin", "Lei Shen" },
            4,
        },
        {
            "wall_reason",
            "medium",
            "The Serpent's Spine was built to hold back which people?",
            { "Mantid", "Yaungol", "Hozen", "Jinyu", "Saurok", "Grummles" },
            1,
        },
        {
            "lore_recorders",
            "easy",
            "Which group chronicles and studies Pandaria's history?",
            { "The Klaxxi", "The Lorewalkers", "The Tillers", "The Anglers" },
            2,
        },
    }
)

Quiz.Lore:Add("mop", "Mists of Pandaria", "https://worldofwarcraft.blizzard.com/en-gb/news/24242434", {
    {
        "resurrectors",
        "medium",
        "Who stole Lei Shen's remains and resurrected him?",
        { "The Shado-Pan", "The Golden Lotus", "The Zandalari", "The Klaxxi" },
        3,
    },
    {
        "nalak_title",
        "hard",
        "Nalak bears which title on the Isle of Thunder?",
        { "The Windlord", "The Tidehunter", "The Thunder King", "The Storm Lord", "The Stormbinder" },
        4,
    },
    {
        "oondasta_island",
        "medium",
        "Which island is home to the Zandalari experiment Oondasta?",
        { "The Isle of Giants", "The Timeless Isle", "The Isle of Thunder", "The Wandering Isle" },
        1,
    },
    {
        "mogu_observer",
        "medium",
        "Who studies the mortal races and the ancient mogu empire during Lei Shen's return?",
        { "Sabellian", "Wrathion", "Ebyssian", "Nefarian" },
        2,
    },
    {
        "giants_position",
        "hard",
        "The Isle of Giants lies north of which region?",
        { "The Jade Forest", "Krasarang Wilds", "Kun-Lai Summit", "The Valley of the Four Winds" },
        3,
    },
    {
        "neutral_assault",
        "hard",
        "Which neutral force campaigns specifically to defeat the resurrected Thunder King?",
        { "The August Celestials", "The Lorewalkers", "The Golden Lotus", "The Shado-Pan Assault" },
        4,
    },
})

Quiz.Lore:Add(
    "mop",
    "Mists of Pandaria",
    "https://worldofwarcraft.blizzard.com/en-gb/news/10051637/mists-of-pandaria-zone-preview-dread-wastes",
    {
        {
            "mantid_empress",
            "easy",
            "Who rules the mantid from the Heart of Fear during Mists of Pandaria?",
            { "Grand Empress Shek'zeer", "Queen Azshara", "Grand Magistrix Elisande", "Queen Talanji" },
            1,
        },
        {
            "empress_corruption",
            "medium",
            "Which sha drives Empress Shek'zeer into madness?",
            { "The Sha of Hatred", "The Sha of Fear", "The Sha of Pride", "The Sha of Doubt" },
            2,
        },
        {
            "paragon_preservation",
            "medium",
            "In what substance were ancient Klaxxi paragons preserved?",
            { "Jade", "Ice", "Amber", "Obsidian", "Crystal", "Stone" },
            3,
        },
        {
            "brewing_tree",
            "hard",
            "Which trees provide the sap used by Dread Wastes brewmasters?",
            { "Ironbark trees", "Dreaming trees", "Greatwoods", "Kypari trees" },
            4,
        },
        {
            "sap_brewgarden",
            "very_hard",
            "Where do Dread Wastes sapmasters brew kypari sap?",
            { "Sunset Brewgarden", "Halfhill Market", "Dawn's Blossom", "Greenstone Village", "Thunderfoot Ranch" },
            1,
        },
        {
            "mantid_council",
            "medium",
            "Which council safeguards mantid history and culture?",
            { "The Golden Lotus", "The Klaxxi", "The August Celestials", "The Shado-Pan" },
            2,
        },
        {
            "early_swarm",
            "very_hard",
            "How early is Shek'zeer's great swarm compared with its expected cycle?",
            { "About one year", "About five years", "About ten years", "About fifty years" },
            3,
        },
        {
            "southern_survivors",
            "hard",
            "What brought the Anglers beyond the wall to the Dread Wastes' southern coast?",
            { "An imperial invitation", "A portal accident", "A mogu summons", "A shipwreck" },
            4,
        },
    }
)
