-- The required TOC dependency loads Orbit-Quiz first; this separate addon uses only its public registration API.
OrbitQuiz:RegisterQuestionPack({
    id = "example_everyday",
    title = "Example: Everyday Trivia",
    version = 1,
    author = "Your name",
    locale = "enUS",
    rules = {
        version = 1,
        answerSeconds = 15,
        revealSeconds = 3,
        allowAnswerChanges = true,
        shuffleQuestions = true,
        shuffleChoices = true,
        repeatQuestions = true,
        questionLimit = 0,
        correctPoints = 1,
        speedBonusPerSecond = 0.1,
        wrongPenaltyStart = 1,
        wrongPenaltyEnd = 0.5,
        wrongPenaltyCurve = 2.5,
        streakBonusPerCorrect = 0.1,
        streakBonusMax = 0.5,
    },
    questions = {
        {
            id = "triangle_sides",
            prompt = "How many sides does a triangle have?",
            choices = { "Two", "Three", "Four", "Five" },
            correctIndex = 2,
            explanation = "A triangle has three sides.",
            category = "Everyday Trivia",
        },
        {
            id = "minutes_per_hour",
            prompt = "How many minutes are in one hour?",
            choices = { "30", "45", "60", "100" },
            correctIndex = 3,
            explanation = "One hour contains 60 minutes.",
            category = "Everyday Trivia",
        },
        {
            id = "keyboard_strings",
            prompt = "Which instrument normally has keys, pedals and strings?",
            choices = { "Piano", "Trumpet", "Flute", "Drum" },
            correctIndex = 1,
            explanation = "An acoustic piano uses keys and pedals to play and control its strings.",
            category = "Everyday Trivia",
        },
    },
})
